language: csharp
solution: VerbalExpressions.sln
install:
  - nuget restore  VerbalExpressions.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release  VerbalExpressions.sln
  - mono ./testrunner/NUnit.Runners.3.0.1/tools/nunit-console.exe ./VerbalExpressionsUnitTests/bin/Release/VerbalExpressionsUnitTests.dll